### ISSUE TITLE
Team_Intro pop up 之後背景可以滑動

### ISSUE THREAD

**Issue by joan0802** [Official-Meichu-Hackathon/2023-mc-ten-year-web-v2#3]
<img width="1470" alt="image" src="https://github.com/Official-Meichu-Hackathon/2023-mc-ten-year-web-v2/assets/122168872/e6f50fb3-7f5f-4757-87d9-77a5a4ba97a1">
@ritmoHung @r1407p @wl00795897 @joan0802 @atticus453

**Comment by ritmo-v0** [comment]
Solved through branch dev commit [7aeec4](https://github.com/Official-Meichu-Hackathon/2023-mc-ten-year-web-v2/commit/7aeec44861205159624e3e7d2f5a6288fc4d7f98).

Checkout the effect at [here](https://tenyeartest.vercel.app/).
